---
- name: reload nginx
  service: name=nginx state=reloaded

- name: validate syntax
  command: nginx -t -c /etc/nginx/nginx.conf
  changed_when: False

- name: restart challenge-app
  service: name=challenge-app state=restarted

- name: Install packages based on package.json
  npm: path=/opt/app
  notify:
    - restart challenge-app
