---
- name: Install nginx package 
  package: name=nginx state=installed

- name: Create log directory and set permissions
  file: state=directory mode=755 path=/var/log/nginx owner=nginx group=nginx

# Nginx setup.
- name: Copy nginx configuration in place.
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - validate syntax
    - reload nginx

- name: Make sure nginx starts at boot
  service: name=nginx state=started enabled=yes

- name: Install libsemanage-python which is required by ansible so we can manage selinux booleans
  package: name=libsemanage-python state=installed 

- name: Make selinux allow nginx to connect to backend machine
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
